## 🧪 Jupyter Notebook 快速入门

`顾燚 (Yi Gu)`

> 在本教程编写过程中，没有AI模型受到伤害！

### 1. Jupyter 的前世今生

**Jupyter** 这个名字是怎么来的？
它是三门语言的缩写：
-   **Ju**: **Ju**lia (下一位顾辰老师的主场)
-   **Pyt**: **Pyt**hon (刚刚何助教讲过的)
-   **eR**: **R** (统计学常用语言，不涉及)

**核心架构**：
1.  **Notebook (前端)**: 你看到的网页或 VS Code 界面
2.  **Kernel (内核)**: 后台负责计算的“大脑”
3.  **IPython**: Python 语言的内核实现
    *   这也是为什么接下来我们要讲的包以 `ipy-` 开头（如 `ipykernel`, `ipywidgets`）

In [14]:
# 让我们看看当前的“大脑”
import sys
import IPython

print(f"当前 Python 解释器路径: {sys.executable}")
print(f"当前 Python 版本: {sys.version}")
print(f"当前 IPython 内核版本: {IPython.__version__}")
# Tip: 如果你的代码跑不通，首先检查右上角的 Kernel (内核) 是否选对！

当前 Python 解释器路径: d:\doc\py\mmda\.venv\Scripts\python.exe
当前 Python 版本: 3.12.9 (main, Feb 12 2025, 14:52:31) [MSC v.1942 64 bit (AMD64)]
当前 IPython 内核版本: 9.11.0

### 2. 基础操作与快捷键 (Cheat Sheet)

Jupyter 的操作核心是 **Cell (单元格)**。

*   **运行代码**: `Shift + Enter` (运行并选中下一行，**最常用**)
*   **运行代码**: `Ctrl + Enter` (运行并停留在当前行)
*   **切换模式**:
    *   `Esc`: 进入**命令模式** (左侧蓝条)，可以按 `A` (Above) 在上方插入，按 `B` (Below) 在下方插入。
    *   `Enter`: 进入**编辑模式** (左侧蓝条变色)，开始写代码。
*   **切换类型**:
    *   `M`: 变为 **Markdown** (写笔记)。
    *   `Y`: 变为 **Code** (写代码)。

Cell 分为 **Code Cell** 和 **Markdown Cell** 两种类型，分别用于写代码和写笔记。

Jupyter 支持 LaTeX 语法，可以在 Markdown Cell 中写数学公式，例如：

例如，著名的欧拉公式：
$$ e^{i\pi} + 1 = 0 $$

或者正态分布公式：
$$ f(x) = \frac{1}{\sigma\sqrt{2\pi}} e^{ -\frac{1}{2}\left(\frac{x-\mu}{\sigma}\right)^2 } $$

### 2.5 魔法命令：感叹号的作用

有时候你需要运行终端命令（比如安装包、查看文件），不需要切换窗口。
在 Jupyter 里，**以感叹号 `!` 开头的代码**会被直接发送给系统终端执行。

*   `!pip install ...`: 安装缺失的包（最常用，但不推荐，现在推荐使用 `%pip install ...`，后面会介绍魔法命令）。
*   `!ls` (Mac/Linux) / `!dir` (Windows): 查看当前目录下的文件。

In [15]:
# For Linux/MacOS:
!pwd

'pwd' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

In [16]:
# For Windows:
!echo %cd%

d:\doc\py\mmda\notebook

In [17]:
!python --version

Python 3.12.9

### 3. 输出机制：Implicit Display vs Print

Jupyter 有一个 **REPL (Read-Eval-Print Loop)** 特性：
*   **默认行为**：Cell 的**最后一行**如果是一个变量，Jupyter 会自动调用 `display()` 展示它。
*   **坑点**：如果你在一个 Cell 里写了多个变量，默认只会显示最后一个！

In [18]:
from IPython.display import display

a = "Hello Output"
b = "Hidden Variable"
c = {"Course": "Pre-lecture", "Role": "TA", "Name": "Gu Yi"}

print("--- 1. 普通 Python 脚本的行为 ---")
a  # 哑巴：在普通脚本里这行没用，在 Jupyter 若不是最后一行也不显示

print("--- 2. Jupyter 的默认行为 (REPL) ---")
# 只有最后一行会被自动 display
c

--- 1. 普通 Python 脚本的行为 ---
--- 2. Jupyter 的默认行为 (REPL) ---

{'Course': 'Pre-lecture', 'Role': 'TA', 'Name': 'Gu Yi'}

In [19]:
print("--- 3. 如果想看所有变量怎么办？ ---")
# 使用 display() 函数，它比 print() 更强大，能渲染富文本
display(a)
display(c)

--- 3. 如果想看所有变量怎么办？ ---

'Hello Output'

{'Course': 'Pre-lecture', 'Role': 'TA', 'Name': 'Gu Yi'}

### 4. 上帝视角：变量查看器与 Data Wrangler

做数据分析时，不要用 `print` 刷屏！
VS Code 提供了类似 Matlab Workspace 的功能。

**操作步骤**：
1. 运行下面的代码生成数据。
2. 点击 VS Code 编辑器顶部的 **【变量 (Variables)】** 按钮。
3. 点击变量旁边的 **表格图标**，启动 Data Viewer / Data Wrangler。

In [20]:
# 这一步需要安装 pandas: pip install pandas
import pandas as pd
import numpy as np

# 模拟一份 100 人的成绩单
df = pd.DataFrame(
    {
        "Name": [f"Student_{i}" for i in range(1, 101)],
        "Math": np.random.normal(80, 10, 100).astype(int),  # 正态分布
        "Physics": np.random.randint(50, 100, 100),  # 随机整数
        "Grade": np.random.choice(["A", "B", "C", "D"], 100),  # 评级
        "Status": ["Normal"] * 90 + ["Absent"] * 10,  # 模拟缺失数据
    }
)

print(df)
display(df)
# 尝试在 Data Viewer 里点击表头排序，或者查看 'Math' 列的分布直方图

           Name  Math  Physics Grade  Status
0     Student_1    83       92     C  Normal
1     Student_2    87       60     A  Normal
2     Student_3    87       99     C  Normal
3     Student_4    77       72     B  Normal
4     Student_5    87       81     A  Normal
..          ...   ...      ...   ...     ...
95   Student_96    67       93     B  Absent
96   Student_97    87       82     C  Absent
97   Student_98    58       66     D  Absent
98   Student_99    81       64     A  Absent
99  Student_100    87       59     D  Absent

[100 rows x 5 columns]

           Name  Math  Physics Grade  Status
0     Student_1    83       92     C  Normal
1     Student_2    87       60     A  Normal
2     Student_3    87       99     C  Normal
3     Student_4    77       72     B  Normal
4     Student_5    87       81     A  Normal
..          ...   ...      ...   ...     ...
95   Student_96    67       93     B  Absent
96   Student_97    87       82     C  Absent
97   Student_98    58       66     D  Absent
98   Student_99    81       64     A  Absent
99  Student_100    87       59     D  Absent

[100 rows x 5 columns]

In [21]:
df.head()

        Name  Math  Physics Grade  Status
0  Student_1    83       92     C  Normal
1  Student_2    87       60     A  Normal
2  Student_3    87       99     C  Normal
3  Student_4    77       72     B  Normal
4  Student_5    87       81     A  Normal

In [22]:
df.describe()

             Math     Physics
count  100.000000  100.000000
mean    77.730000   76.240000
std      9.479222   15.139833
min     55.000000   50.000000
25%     72.000000   61.750000
50%     78.000000   76.000000
75%     84.000000   90.000000
max    100.000000   99.000000

### 5. 可视化与交互 (Interactive)

Jupyter 最方便的地方在于“所见即所得”的交互。
我们使用 `ipywidgets` (基于 IPython 的组件) 来实现。

In [23]:
# 这一步需要安装 matplotlib 和 ipywidgets
import matplotlib.pyplot as plt
from ipywidgets import interact


# 定义一个绘图函数
def plot_wave(frequency=1.0, amplitude=1.0, color="blue"):
    x = np.linspace(0, 2 * np.pi, 200)
    y = amplitude * np.sin(frequency * x)

    plt.figure(figsize=(8, 4))
    plt.plot(x, y, color=color, linewidth=3)
    plt.ylim(-5.5, 5.5)
    plt.grid(True, alpha=0.3)
    plt.title(f"Wave: y = {amplitude} * sin({frequency} * x)")
    plt.show()


# 启动交互！拖动滑块试试
print("交互式演示：请拖动下方滑块")
interact(
    plot_wave,
    frequency=(0.5, 5.0, 0.1),
    amplitude=(0.1, 5.0, 0.1),
    color=["blue", "red", "green", "orange"],
);

交互式演示：请拖动下方滑块

interactive(children=(FloatSlider(value=1.0, description='frequency', max=5.0, min=0.5), FloatSlider(value=1.0…

In [24]:
import plotly.graph_objects as go
import numpy as np

x = np.linspace(-5, 5, 100)
y = np.linspace(-5, 5, 100)
x_grid, y_grid = np.meshgrid(x, y)
r = np.sqrt(x_grid**2 + y_grid**2)
z = np.sin(r) / r  # sinc 函数

fig = go.Figure(data=[go.Surface(z=z, x=x, y=y)])

fig.update_layout(
    title="Interactive 3D Sinc Function (Try rotating me!)",
    autosize=True,
    width=800,
    height=600,
    margin=dict(l=65, r=50, b=65, t=90),
    scene=dict(xaxis_title="X Axis", yaxis_title="Y Axis", zaxis_title="Z Amplitude"),
)

fig.show()

In [25]:
import plotly.express as px

df = px.data.stocks()

fig = px.line(
    df,
    x="date",
    y=df.columns[1:],
    title="Tech Stocks Over Time (Zoom with the slider below!)",
)

fig.update_xaxes(rangeslider_visible=True)
fig.show()

### 6. 进阶：魔法命令

Jupyter 还支持一些特殊的“魔法命令”，以 `%` 或 `%%` 开头，可以实现一些高级功能。
例如：
*   `%timeit`: 测量代码运行时间。
*   `%%writefile`: 将 Cell 内容写入文件。
*   `%matplotlib inline`: 在 Notebook 内直接显示 Matplotlib 图表。

In [26]:
print("测试生成一百万个随机数的时间：")
%timeit np.random.rand(1000000)

测试生成一百万个随机数的时间：
6.86 ms ± 21.6 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)

### 7. 总结与资源

- **Overleaf 预告**: Jupyter 支持 LaTeX 公式，如 $E=mc^2$，下一位武鹏助教将在 Overleaf 中深入讲解。
- **Julia 预告**: 只需要切换 Kernel，这个 Notebook 就能跑 Julia 代码，有请顾辰老师！

**推荐资源**:
- [VS Code Jupyter 官方文档](https://code.visualstudio.com/docs/datascience/jupyter-notebooks)
- 遇到报错：请检查左下角/右上角的 **Kernel** 环境是否正确。